"""Durable implementation provenance: exactly what source ran, and where it
came from.

A model-backed engineer turns a structured model reply into source code and
runs it. The run's *result* is already durable (the evidence store, the run
directory, the manifest); what would otherwise evaporate is the link between
that result and the implementation event that produced it — which bytes ran,
generated from which template, by which provider reply, under which request.
This module makes that link a durable record with the same invariant as
every other store here: **an id never maps to different content.**

Two content-addressed layers, deliberately separate:

* **Source trees** (``sources/<source_id>/``) carry pure content identity:
  the same generated bytes are the same source, however many replies
  produced them. Two invocations that generate identical code share one
  tree — which is precisely what makes "did the rerun execute the same
  implementation?" answerable by id comparison.
* **Implementation records** (``implementations/<id>.json``) carry the
  provenance of one *generation event*: the template it started from, the
  request fingerprint, the response occurrence id, the provider and served
  model, the rationale the model gave, and the exact job binding
  (entrypoint, command, config, seed, required artifacts). The id is
  content-derived over all of it — and because a response occurrence id
  participates, two generations are two records even when their source is
  byte-identical.

Writes are write-once and verify-on-repeat: re-recording identical content
is a no-op, re-recording different content under the same id raises.
Rejected generation attempts — replies that failed deterministic source
validation and never executed — are preserved under ``rejected/`` as JSON
payloads (never materialized as files at model-chosen paths), because a
refused implementation is part of the record, not litter.

Nothing here touches scientific state, and nothing here may ever hold a
credential: records store fingerprints, ids and source text, not keys.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

from ..core.ids import content_id, occurrence_id
from ..core.types import ConfigValue, freeze_mapping

_SOURCES_DIRNAME = "sources"
_RECORDS_DIRNAME = "implementations"
_REJECTED_DIRNAME = "rejected"
_RECORD_SUFFIX = ".json"


class ImplementationConflictError(RuntimeError):
    """Raised when an implementation id or source id is re-recorded with
    different content. Ids are permanent names; renaming their content is
    exactly the corruption this store exists to make loud."""


class ImplementationIntegrityError(RuntimeError):
    """Raised when a stored record no longer matches the id it is filed
    under. A tampered or corrupted record fails on load, never becomes
    trusted provenance."""


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


@dataclass(frozen=True, slots=True)
class SourceFile:
    """One generated file, named by a path the *trusted* caller already
    validated — this module stores what it is given and never interprets
    paths beyond joining them under the tree root."""

    path: str
    content: str

    @property
    def sha256(self) -> str:
        return sha256_text(self.content)


def source_tree_id(files: Sequence[SourceFile]) -> str:
    """Content identity of a source tree: identical bytes, identical id."""
    manifest = tuple(
        (f.path, f.sha256) for f in sorted(files, key=lambda f: f.path)
    )
    return content_id("src", manifest)


@dataclass(frozen=True, slots=True)
class ImplementationRecord:
    """The provenance of one implementation event, id-stable forever.

    ``manifest`` (path -> sha256) plus ``source_id`` pin the exact bytes;
    the request fingerprint, response occurrence id and provider fields pin
    the generation; entrypoint, command, config, seed and required
    artifacts pin the binding that executed it. The id is derived from all
    of it, so the same id can never later name a different implementation.
    """

    invocation_id: str
    action_type: str
    spec_id: str
    template_id: str
    template_sha256: str
    source_id: str
    manifest: Mapping[str, str]
    entrypoint: str
    command: tuple[str, ...]
    config: Mapping[str, ConfigValue]
    seed: int | None
    required_artifacts: tuple[str, ...]
    request_fingerprint: str
    response_id: str
    provider: str
    requested_model: str
    served_model: str
    provider_request_id: str | None
    rationale: str
    id: str = field(default="")

    def __post_init__(self) -> None:
        object.__setattr__(self, "manifest", freeze_mapping(self.manifest))
        object.__setattr__(self, "config", freeze_mapping(self.config))
        if not self.id:
            object.__setattr__(self, "id", content_id("impl", *self._identity()))

    def _identity(self) -> tuple[object, ...]:
        """The fields the id derives from — the generation event and its
        source. ``command``, ``config`` and ``required_artifacts`` are
        preserved on the record but excluded here: they are trusted binding
        output, and ``config`` embeds this very id as the job's provenance
        link, which an id cannot derive from. The store's write-once guard
        still compares the *full* payload, so the same id can never quietly
        acquire a different binding either."""
        return (
            self.invocation_id,
            self.action_type,
            self.spec_id,
            self.template_id,
            self.template_sha256,
            self.source_id,
            self.manifest,
            self.entrypoint,
            self.seed,
            self.request_fingerprint,
            self.response_id,
            self.provider,
            self.requested_model,
            self.served_model,
            self.provider_request_id,
            self.rationale,
        )


class ImplementationStore:
    """File-backed, write-once storage for source trees, implementation
    records, and rejected generation attempts, under one injected root."""

    def __init__(self, root: Path | str) -> None:
        self._root = Path(root)
        self._root.mkdir(parents=True, exist_ok=True)

    @property
    def root(self) -> Path:
        return self._root

    # -- source trees --------------------------------------------------------

    def source_dir(self, source_id: str) -> Path:
        return self._root / _SOURCES_DIRNAME / source_id

    def persist_source(self, files: Sequence[SourceFile]) -> tuple[str, Path]:
        """Write ``files`` as a content-addressed tree; return its id and
        directory. Re-persisting identical content is a no-op; a tree that
        already exists with different bytes raises."""
        if not files:
            raise ValueError("a source tree must contain at least one file")
        source_id = source_tree_id(files)
        tree = self.source_dir(source_id)
        if tree.exists():
            self._verify_tree(source_id, tree, files)
            return source_id, tree
        tree.mkdir(parents=True)
        for source in files:
            target = tree / source.path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(source.content, encoding="utf-8")
        return source_id, tree

    def _verify_tree(
        self, source_id: str, tree: Path, files: Sequence[SourceFile]
    ) -> None:
        on_disk = {
            str(p.relative_to(tree)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in tree.rglob("*")
            if p.is_file()
        }
        expected = {f.path: f.sha256 for f in files}
        if on_disk != expected:
            raise ImplementationConflictError(
                f"source tree {source_id} already exists with different "
                f"content; source ids are permanent names"
            )

    # -- implementation records ----------------------------------------------

    def _record_path(self, implementation_id: str) -> Path:
        return (
            self._root / _RECORDS_DIRNAME / f"{implementation_id}{_RECORD_SUFFIX}"
        )

    def record(self, record: ImplementationRecord) -> ImplementationRecord:
        """Store one record, write-once. Identical re-recording is a no-op;
        different content under the same id raises."""
        existing = self.get(record.id)
        if existing is not None:
            if existing != record:
                raise ImplementationConflictError(
                    f"implementation {record.id} is already recorded with "
                    f"different content; records are never rewritten"
                )
            return existing
        path = self._record_path(record.id)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(_to_payload(record), indent=2, sort_keys=True),
            encoding="utf-8",
        )
        return record

    def get(self, implementation_id: str) -> ImplementationRecord | None:
        path = self._record_path(implementation_id)
        if not path.exists():
            return None
        # The id is recomputed from what was read, never trusted from the
        # file: a record that no longer hashes to its name fails loudly.
        record = _from_payload(json.loads(path.read_text(encoding="utf-8")))
        if record.id != implementation_id:
            raise ImplementationIntegrityError(
                f"record filed under {implementation_id} re-derives id "
                f"{record.id}; refusing to load a record that no longer "
                f"matches its name"
            )
        return record

    def records(self) -> tuple[ImplementationRecord, ...]:
        directory = self._root / _RECORDS_DIRNAME
        if not directory.exists():
            return ()
        loaded = []
        for path in sorted(directory.glob(f"*{_RECORD_SUFFIX}")):
            record = self.get(path.stem)
            assert record is not None  # listed from the directory just above
            loaded.append(record)
        return tuple(loaded)

    # -- rejected attempts ---------------------------------------------------

    def preserve_rejected(
        self,
        *,
        invocation_id: str,
        spec_id: str,
        reason: str,
        request_fingerprint: str,
        response_id: str,
        payload: object,
    ) -> Path:
        """Preserve one refused generation attempt as data.

        The payload is stored as JSON, never materialized as files: a
        rejected reply may name unsafe paths, and preserving evidence must
        not mean honouring them. Returns the file written."""
        directory = self._root / _REJECTED_DIRNAME
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / f"{occurrence_id('rej')}{_RECORD_SUFFIX}"
        path.write_text(
            json.dumps(
                {
                    "invocation_id": invocation_id,
                    "spec_id": spec_id,
                    "reason": reason,
                    "request_fingerprint": request_fingerprint,
                    "response_id": response_id,
                    "payload": _jsonable(payload),
                },
                indent=2,
                sort_keys=True,
            ),
            encoding="utf-8",
        )
        return path

    def rejected(self) -> tuple[Mapping[str, object], ...]:
        directory = self._root / _REJECTED_DIRNAME
        if not directory.exists():
            return ()
        return tuple(
            json.loads(path.read_text(encoding="utf-8"))
            for path in sorted(directory.glob(f"*{_RECORD_SUFFIX}"))
        )


def _jsonable(value: object) -> object:
    """A JSON-serializable copy of ``value``; anything unrepresentable is
    preserved as its ``repr`` rather than dropped."""
    if isinstance(value, Mapping):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return repr(value)


def _to_payload(record: ImplementationRecord) -> dict[str, object]:
    return {
        "id": record.id,
        "invocation_id": record.invocation_id,
        "action_type": record.action_type,
        "spec_id": record.spec_id,
        "template_id": record.template_id,
        "template_sha256": record.template_sha256,
        "source_id": record.source_id,
        "manifest": dict(record.manifest),
        "entrypoint": record.entrypoint,
        "command": list(record.command),
        "config": dict(record.config),
        "seed": record.seed,
        "required_artifacts": list(record.required_artifacts),
        "request_fingerprint": record.request_fingerprint,
        "response_id": record.response_id,
        "provider": record.provider,
        "requested_model": record.requested_model,
        "served_model": record.served_model,
        "provider_request_id": record.provider_request_id,
        "rationale": record.rationale,
    }


def _from_payload(payload: Mapping[str, object]) -> ImplementationRecord:
    manifest = payload["manifest"]
    config = payload["config"]
    command = payload["command"]
    required = payload["required_artifacts"]
    seed = payload["seed"]
    provider_request_id = payload["provider_request_id"]
    assert isinstance(manifest, Mapping)
    assert isinstance(config, Mapping)
    assert isinstance(command, list)
    assert isinstance(required, list)
    return ImplementationRecord(
        invocation_id=str(payload["invocation_id"]),
        action_type=str(payload["action_type"]),
        spec_id=str(payload["spec_id"]),
        template_id=str(payload["template_id"]),
        template_sha256=str(payload["template_sha256"]),
        source_id=str(payload["source_id"]),
        manifest={str(k): str(v) for k, v in manifest.items()},
        entrypoint=str(payload["entrypoint"]),
        command=tuple(str(part) for part in command),
        config={str(k): _config_value(v) for k, v in config.items()},
        seed=int(seed) if isinstance(seed, int) else None,
        required_artifacts=tuple(str(part) for part in required),
        request_fingerprint=str(payload["request_fingerprint"]),
        response_id=str(payload["response_id"]),
        provider=str(payload["provider"]),
        requested_model=str(payload["requested_model"]),
        served_model=str(payload["served_model"]),
        provider_request_id=(
            str(provider_request_id) if provider_request_id is not None else None
        ),
        rationale=str(payload["rationale"]),
    )


def _config_value(value: object) -> ConfigValue:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    raise ImplementationIntegrityError(
        f"config value {value!r} is not a scalar; the stored record is "
        f"corrupt"
    )
